Repository joostlek/python-opensky, pull requests merged in 2023-06, with the labels that each got.

#38 Use parametrize for tests
  src/python_opensky/opensky.py
  tests/test_radius.py
Labels: enhancement

#39 Make linter work on PR
  .github/workflows/linting.yaml
Labels: enhancement, github_actions

#35 Improve bounding box calculations
  src/python_opensky/opensky.py
  tests/test_radius.py
Labels: enhancement

#50 Fix no returned states in request
  src/python_opensky/opensky.py
  tests/fixtures/unavailable_states.json
  tests/test_states.py
Labels: bugfix
